version: '3.8'
services:
  app:
    build: src
    ports:
      - "8080:8080"
    environment:
      SPRING_R2DBC_URL: r2dbc:h2:mem:///testdb
      SPRING_R2DBC_USERNAME: sa
      SPRING_R2DBC_PASSWORD:
      SPRING_R2DBC_POOL_ENABLED: "true"
      SPRING_FLYWAY_LOCATIONS: classpath:db/migration
    depends_on:
      - h2db

  h2db:
    image: oscarfonts/h2
    ports:
      - "1521:1521"