server:
  port: 8080

logging:
  level:
    ROOT: INFO

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres
    username: postgres
    password:
  flyway:
    url: jdbc:postgresql://localhost:5432/postgres
    user: postgres
    password: