INSERT INTO products (id, name, price) VALUES (1, 'T-Shirt', 2000);
INSERT INTO products (id, name, price) VALUES (2, 'Jeans', 5000);
INSERT INTO products (id, name, price) VALUES (3, 'Sweatshirt', 3500);
INSERT INTO products (id, name, price) VALUES (4, 'Laptop', 80000);
INSERT INTO products (id, name, price) VALUES (5, 'Smartphone', 120000);
INSERT INTO products (id, name, price) VALUES (6, 'Headphones', 2500);
INSERT INTO products (id, name, price) VALUES (7, 'Coffee Maker', 4000);
INSERT INTO products (id, name, price) VALUES (8, 'Watch', 7000);
INSERT INTO products (id, name, price) VALUES (9, 'Book', 1500);
INSERT INTO products (id, name, price) VALUES (10, 'Desk Lamp', 1000);
INSERT INTO products (id, name, price) VALUES (11, 'Backpack', 3000);
INSERT INTO products (id, name, price) VALUES (12, 'Tablet', 50000);
INSERT INTO products (id, name, price) VALUES (13, 'Camera', 10000);
INSERT INTO products (id, name, price) VALUES (14, 'Speakers', 5000);
INSERT INTO products (id, name, price) VALUES (15, 'Fitness Tracker', 2000);
INSERT INTO products (id, name, price) VALUES (16, 'Toaster', 1500);
INSERT INTO products (id, name, price) VALUES (17, 'Blender', 3000);
INSERT INTO products (id, name, price) VALUES (18, 'Vacuum Cleaner', 6000);
INSERT INTO products (id, name, price) VALUES (19, 'Television', 150000);
INSERT INTO products (id, name, price) VALUES (20, 'Video Game Console', 40000);