INSERT INTO products (name, price) VALUES ('T-Shirt', 2000);
INSERT INTO products (name, price) VALUES ('Jeans', 5000);
INSERT INTO products (name, price) VALUES ('Sweatshirt', 3500);
INSERT INTO products (name, price) VALUES ('Laptop', 80000);
INSERT INTO products (name, price) VALUES ('Smartphone', 120000);
INSERT INTO products (name, price) VALUES ('Headphones', 2500);
INSERT INTO products (name, price) VALUES ('Coffee Maker', 4000);
INSERT INTO products (name, price) VALUES ('Watch', 7000);
INSERT INTO products (name, price) VALUES ('Book', 1500);
INSERT INTO products (name, price) VALUES ('Desk Lamp', 1000);
INSERT INTO products (name, price) VALUES ('Backpack', 3000);
INSERT INTO products (name, price) VALUES ('Tablet', 50000);
INSERT INTO products (name, price) VALUES ('Camera', 10000);
INSERT INTO products (name, price) VALUES ('Speakers', 5000);
INSERT INTO products (name, price) VALUES ('Fitness Tracker', 2000);
INSERT INTO products (name, price) VALUES ('Toaster', 1500);
INSERT INTO products (name, price) VALUES ('Blender', 3000);
INSERT INTO products (name, price) VALUES ('Vacuum Cleaner', 6000);
INSERT INTO products (name, price) VALUES ('Television', 150000);
INSERT INTO products (name, price) VALUES ('Video Game Console', 40000);